# Generated by Django 3.2.6 on 2021-08-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('session_id', 'category', 'name', 'data', 'timestamp')},
        ),
    ]
