# Generated by Django 3.2.6 on 2021-08-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0002_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
